language: objective-c
osx_image: xcode11.7
script: 
  - xcodebuild -project Dop.xcodeproj -scheme DopTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=13.7' test
